spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.88:3306/study?useUnicode=true&characterEncoding=utf-8
    username: test
    password: 1234
  mail:
    host: smtp.163.com
    username: jinze1791209985@163.com
    password: PCEQTJKBPGJQBAYS
    properties:
      from: jinze1791209985@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
